title: Mercy Dufie Boateng
logo: /Images/HeadShot.png
description: 
  <br><br>
  <a href=""https://www.linkedin.com/in/mercydufieboateng"">View My LinkedIn Profile</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
